# Generated by Django 4.2.17 on 2024-12-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_heartbeat_iccardinfopush_strangercapture_verifypush_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iccardinfopush',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
