# Generated by Django 4.2.17 on 2024-12-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_iccardinfopush_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iccardinfopush',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
