# Generated by Django 4.2.17 on 2024-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_iccardinfopush_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeat',
            options={'ordering': ['-time'], 'verbose_name': 'Heartbeat', 'verbose_name_plural': 'Heartbeats'},
        ),
        migrations.AlterModelOptions(
            name='iccardinfopush',
            options={'verbose_name': 'ICCard Info Push', 'verbose_name_plural': 'ICCard Info Pushes'},
        ),
        migrations.AlterModelOptions(
            name='strangercapture',
            options={'verbose_name': 'Stranger Capture', 'verbose_name_plural': 'Stranger Captures'},
        ),
        migrations.AlterModelOptions(
            name='verifypush',
            options={'verbose_name': 'Verify Push', 'verbose_name_plural': 'Verify Pushes'},
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='id_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='mj_card_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='native',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='person_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='rfid_card',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verifypush',
            name='telnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='verifypush',
            table='verify_push',
        ),
    ]
