# Generated by Django 4.2.17 on 2024-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_alter_heartbeat_options_alter_iccardinfopush_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifypush',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
