# Generated by Django 4.2.17 on 2025-02-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_verifypush_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('cfiletype', models.IntegerField(blank=True, null=True)),
                ('cfileindex', models.IntegerField(blank=True, null=True)),
                ('cfilepos', models.IntegerField(blank=True, null=True)),
                ('similarity', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('dwfiletype', models.IntegerField(blank=True, null=True)),
                ('dwfileindex', models.IntegerField(blank=True, null=True)),
                ('dwfilepos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrangerCaptureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.BigIntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dwfiletype', models.BigIntegerField(blank=True, null=True)),
                ('dwfileindex', models.BigIntegerField(blank=True, null=True)),
                ('dwfilepos', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.BigIntegerField(blank=True, null=True)),
                ('rf_id_card_num', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('dwfiletype', models.BigIntegerField(blank=True, null=True)),
                ('dwfileindex', models.BigIntegerField(blank=True, null=True)),
                ('dwfilepos', models.BigIntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('RanId', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='heartbeat',
            options={'verbose_name': 'Heartbeat', 'verbose_name_plural': 'Heartbeats'},
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='iccardinfopush',
            name='ip_address',
            field=models.CharField(blank=True, default='aniqlanmagan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strangercapture',
            name='ip_address',
            field=models.CharField(blank=True, default='aniqlanmagan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifypush',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['device_id', 'time'], name='basic_app_h_device__ba398c_idx'),
        ),
        migrations.AddIndex(
            model_name='iccardinfopush',
            index=models.Index(fields=['device_id', 'created_at'], name='basic_app_i_device__4ceee9_idx'),
        ),
        migrations.AddIndex(
            model_name='strangercapture',
            index=models.Index(fields=['device_id', 'create_time'], name='basic_app_s_device__ce8c42_idx'),
        ),
        migrations.AddIndex(
            model_name='strangercapture',
            index=models.Index(fields=['direction'], name='basic_app_s_directi_3c33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='verifypush',
            index=models.Index(fields=['person_id', 'verify_status'], name='verify_push_person__55255f_idx'),
        ),
        migrations.AddIndex(
            model_name='verifypush',
            index=models.Index(fields=['create_time'], name='verify_push_create__53dcf4_idx'),
        ),
        migrations.AddIndex(
            model_name='verifypush',
            index=models.Index(fields=['id_card'], name='verify_push_id_card_7c8e12_idx'),
        ),
    ]
