# Generated by Django 4.2.17 on 2025-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_controllog_strangercapturelog_usersmanagement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmanagement',
            options={'verbose_name': 'User Management', 'verbose_name_plural': 'Users Management'},
        ),
        migrations.AddField(
            model_name='controllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='controllog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='controllog'),
        ),
        migrations.AddField(
            model_name='usersmanagement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='controllog',
            unique_together={('face_id', 'name', 'time')},
        ),
    ]
