# Generated by Django 4.2.17 on 2025-01-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_strangercapture_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
