# Generated by Django 4.2.17 on 2025-01-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_alter_heartbeat_ip_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='heartbeat',
            index=models.Index(fields=['device_id', 'time'], name='basic_app_h_device__ba398c_idx'),
        ),
        migrations.AddIndex(
            model_name='iccardinfopush',
            index=models.Index(fields=['device_id', 'created_at'], name='basic_app_i_device__4ceee9_idx'),
        ),
        migrations.AddIndex(
            model_name='strangercapture',
            index=models.Index(fields=['device_id', 'create_time'], name='basic_app_s_device__ce8c42_idx'),
        ),
        migrations.AddIndex(
            model_name='strangercapture',
            index=models.Index(fields=['direction'], name='basic_app_s_directi_3c33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='verifypush',
            index=models.Index(fields=['person_id', 'verify_status'], name='verify_push_person__55255f_idx'),
        ),
        migrations.AddIndex(
            model_name='verifypush',
            index=models.Index(fields=['create_time'], name='verify_push_create__53dcf4_idx'),
        ),
        migrations.AddIndex(
            model_name='verifypush',
            index=models.Index(fields=['id_card'], name='verify_push_id_card_7c8e12_idx'),
        ),
    ]
