# Generated by Django 4.2.17 on 2025-01-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_heartbeat_basic_app_h_device__ba398c_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeat',
            options={'verbose_name': 'Heartbeat', 'verbose_name_plural': 'Heartbeats'},
        ),
        migrations.AddField(
            model_name='verifypush',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
