# Generated by Django 4.2.17 on 2025-01-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_alter_heartbeat_options_verifypush_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
