# Generated by Django 4.2.17 on 2025-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_heartbeat_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('cfiletype', models.IntegerField(blank=True, null=True)),
                ('cfileindex', models.IntegerField(blank=True, null=True)),
                ('cfilepos', models.IntegerField(blank=True, null=True)),
                ('similarity', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('dwfiletype', models.IntegerField(blank=True, null=True)),
                ('dwfileindex', models.IntegerField(blank=True, null=True)),
                ('dwfilepos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrangerCaptureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dwfiletype', models.BigIntegerField(blank=True, null=True)),
                ('dwfileindex', models.BigIntegerField(blank=True, null=True)),
                ('dwfilepos', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.BigIntegerField(blank=True, null=True)),
                ('rf_id_card_num', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('extra_info', models.BigIntegerField(blank=True, null=True)),
                ('dwfiletype', models.BigIntegerField(blank=True, null=True)),
                ('dwfileindex', models.BigIntegerField(blank=True, null=True)),
                ('dwfilepos', models.BigIntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('RanId', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
