# Generated by Django 4.2.17 on 2025-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_controllog_strangercapturelog_usersmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllog',
            name='face_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strangercapturelog',
            name='face_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersmanagement',
            name='face_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
