# Generated by Django 4.2.17 on 2025-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_alter_usersmanagement_rf_id_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmanagement',
            name='name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersmanagement',
            name='rf_id_card_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
