# Generated by Django 4.2.17 on 2025-01-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_alter_usersmanagement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmanagement',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
