# Generated by Django 4.2.17 on 2025-01-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_alter_usersmanagement_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmanagement',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
