# Generated by Django 4.2.17 on 2025-02-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0018_alter_usersmanagement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmanagement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
