# Generated by Django 4.2.17 on 2025-03-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0019_usersmanagement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmanagement',
            options={'verbose_name': 'User Management', 'verbose_name_plural': 'Users Management'},
        ),
        migrations.AddField(
            model_name='controllog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='controllog'),
        ),
    ]
