# Generated by Django 4.2.17 on 2025-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_alter_usersmanagement_options_controllog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
