# Generated by Django 4.2.17 on 2025-03-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0021_controllog_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controllog',
            unique_together={('face_id', 'name', 'time')},
        ),
    ]
