# Generated by Django 4.2.17 on 2025-03-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0023_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='hemis_id',
            field=models.BigIntegerField(),
        ),
    ]
