# Generated by Django 4.2.17 on 2025-03-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_alter_userrole_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='full_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='passport',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.TextField(),
        ),
    ]
